### ISSUE TITLE
Temp 5cm Boden hinzufügen

### ISSUE THREAD

**Issue by MP3Chris2712** [roe-dl/weewx-rwsa#1]
Hallo,

wäre es möglich den 5cm Bodensensor mit ein zubinden ? 

wäre dann Minimum Tag Temp 5cm = extraTemp1

**Comment by roe-dl** [comment]
Unfortunately there is no configuration option for that by now.

You can replace 
```('','','','{:.f}'), # temp 5cm```
by
```('extraTemp1','Day','min','{:.1f}'), # temp 5cm```
in file `regionalwetterSachsenAnhalt.py`.

**Comment by roe-dl** [comment]
Ich habe nun dafür eine Konfigurationsoption hinzugefügt. Sie heißt `T5CM` und gibt die Größe an, die als 5cm-Temperatur verwendet werden soll.

Beispiel:
```
    [[RegionalwetterSachsenAnhalt]]
        ...
        T5CM = extraTemp1
```
